[package]
name = "game_of_life"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"
glium = "0.34.0"
image = "0.24"
winit = "0.29.15"
clearscreen = "3.0.0"
